baseURL = 'https://1blckhrt.github.io/blog/'
languageCode = 'en-us'
title = "blckhrt's blog"
theme = 'PaperMod'

[menu]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  category = "categories"
  tag = "tags"
